# Usage:
#   docker-compose up --detach
version: "3"

services:
    client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
        container_name: visited_places
